services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: mediuser
      POSTGRES_PASSWORD: medipass
      POSTGRES_DB: medidb
    ports:
      - "5432:5432"
    volumes:
      - medi_pgdata:/var/lib/postgresql/data

  backend:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://mediuser:medipass@db:5432/medidb
      DEV_AUTH_TOKEN: testtoken
      FILE_STORAGE_DIR: /data/audio
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      SUPABASE_BUCKET: ${SUPABASE_BUCKET}
      

      
    volumes:
      - ./data/audio:/data/audio
    ports:
      - "8080:8080"

volumes:
  medi_pgdata:
